[project]
name = "litellm-dockerless"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.0",
    "litellm[proxy]>=1.65.4.post1",
    "prisma>=0.15.0",
]
